server:
  port: 8010 #服务端口

eureka:
  server:
    # renewal-percent-threshold: 0.1
    # 关闭自我保护模式
    enable-self-preservation: false
      # Eureka Server 自我保护系数，当enable-self-preservation=true时，启作用
    # renewal-percent-threshold:
    # 设置清理间隔,单位为毫秒,默认为0
    eviction-interval-timer-in-ms: 3000  # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
    wait-time-in-ms-when-sync-empty: 6000000
    # 集群之间相互更新节点信息的时间频率
    peer-eureka-nodes-update-interval-ms: 6000

  instance:
    hostname: 127.0.0.1
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ip-address: 127.0.0.1
    # 心跳间隔
    lease-renewal-interval-in-seconds: 3
    # 服务失效时间： 如果多久没有收到请求，则可以删除服务
    lease-expiration-duration-in-seconds: 7
#  instance:
#    hostname: localhost
  client:
    register-with-eureka: true #是否将eureka自身作为应用注册到eureka注册中心
    fetch-registry: false #为true时，可以启动，但报异常：Cannot execute request on any known server
    # 客户端从Eureka Server集群里更新Eureka Server信息的频率
    eureka-service-url-poll-interval-seconds: 60
    # 定义从注册中心获取注册服务的信息
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/